<?php
/**
 * Pure-PHP QR Code Generator (SVG output).
 *
 * Generates a QR Code SVG entirely in PHP — no external services, no Composer
 * dependencies, no curl calls. Uses the standard QR Error Correction Level M
 * and supports the alphanumeric + byte encoding modes needed for otpauth:// URIs.
 *
 * Algorithm overview
 * ──────────────────
 * 1. Encode the data as a byte-mode QR payload (ISO 18004).
 * 2. Apply Reed-Solomon error correction.
 * 3. Place function patterns (finder, timing, alignment, format info).
 * 4. Fill data modules using the standard 2-column up/down zigzag.
 * 5. Apply all 8 mask patterns, score them, pick the winner.
 * 6. Render to an SVG string.
 *
 * Supported: QR versions 1-10 (up to ~174 bytes with ECC level M), which
 * comfortably covers any otpauth:// URI generated by this plugin.
 *
 * @package WP_Sentinel_Security
 * @since   2.7.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Sentinel_QR
 *
 * Usage:
 *   $svg = Sentinel_QR::generate( 'otpauth://totp/...', 200 );
 *   // $svg is a self-contained <svg>…</svg> string.
 */
class Sentinel_QR {

	// ── Reed-Solomon GF(256) tables ──────────────────────────────────────────

	/** @var int[] GF(256) exponent table (antilog). */
	private static $exp = array();

	/** @var int[] GF(256) logarithm table. */
	private static $log = array();

	/** @var bool Whether GF tables have been initialised. */
	private static $gf_init = false;

	// ── QR format data (hard-coded for ECC level M) ──────────────────────────

	/**
	 * Format information strings for ECC level M (XOR'd with mask pattern).
	 * Index = mask pattern (0-7).  Value = 15-bit format word, MSB first.
	 *
	 * @var int[]
	 */
	private static $format_info = array(
		0b100000011001110, // mask 0
		0b100010110111001, // mask 1
		0b100101010000111, // mask 2
		0b100111101110000, // mask 3
		0b101000100110111, // mask 4
		0b101010011000000, // mask 5
		0b101101111111110, // mask 6
		0b101111000001001, // mask 7 (actually mask 0..7 for ECC M)
	);

	/**
	 * Alignment pattern centre coordinates for QR versions 2-10.
	 * Version 1 has no alignment patterns.
	 *
	 * @var array<int,int[]>
	 */
	private static $alignment_coords = array(
		2  => array( 6, 18 ),
		3  => array( 6, 22 ),
		4  => array( 6, 26 ),
		5  => array( 6, 30 ),
		6  => array( 6, 34 ),
		7  => array( 6, 22, 38 ),
		8  => array( 6, 24, 42 ),
		9  => array( 6, 26, 46 ),
		10 => array( 6, 28, 50 ),
	);

	/**
	 * Data capacity (bytes) for ECC level M, versions 1-10.
	 *
	 * @var int[]
	 */
	private static $capacity_m = array(
		0, // placeholder – versions are 1-based
		13, 22, 34, 48, 64, 84, 93, 122, 154, 195,
	);

	/**
	 * Reed-Solomon error correction code-words (EC codewords) for ECC M.
	 *
	 * @var int[]
	 */
	private static $ec_codewords_m = array(
		0,  // placeholder
		10, 16, 26, 18, 24, 16, 18, 22, 22, 26,
	);

	/**
	 * Number of blocks for ECC level M, versions 1-10.
	 * Each element is [ blocks_group1, data_per_block_g1, blocks_group2, data_per_block_g2 ]
	 *
	 * @var array<int,int[]>
	 */
	private static $block_info = array(
		0 => array( 0, 0, 0, 0 ),
		1 => array( 1, 13, 0, 0 ),
		2 => array( 1, 22, 0, 0 ),
		3 => array( 2, 17, 0, 0 ),
		4 => array( 2, 24, 0, 0 ),
		5 => array( 2, 15, 2, 16 ),
		6 => array( 4, 19, 0, 0 ),
		7 => array( 2, 14, 4, 15 ),
		8 => array( 4, 18, 2, 19 ),
		9 => array( 4, 16, 4, 17 ),
		10 => array( 6, 19, 2, 20 ),
	);

	// ── Public API ────────────────────────────────────────────────────────────

	/**
	 * Generate a QR code SVG for the given data string.
	 *
	 * @param string $data   The string to encode.
	 * @param int    $size   Desired rendered width/height in pixels (default 200).
	 * @param int    $margin Quiet zone in modules (default 4, minimum 4 per spec).
	 * @return string SVG markup, or empty string if data is too long.
	 */
	public static function generate( $data, $size = 200, $margin = 4 ) {
		self::init_gf();

		// 1. Choose minimum version that fits the data.
		$bytes   = array_values( unpack( 'C*', $data ) );
		$n_bytes = count( $bytes );
		$version = 0;
		for ( $v = 1; $v <= 10; $v++ ) {
			if ( $n_bytes <= self::$capacity_m[ $v ] ) {
				$version = $v;
				break;
			}
		}
		if ( 0 === $version ) {
			return ''; // Data too long for supported versions.
		}

		// 2. Build the data codeword stream.
		$data_codewords = self::encode_data( $bytes, $version );

		// 3. Reed-Solomon error correction.
		$all_codewords = self::add_ec( $data_codewords, $version );

		// 4. Build the module grid.
		$size_modules = $version * 4 + 17;
		$grid         = self::build_grid( $version, $size_modules );

		// 5. Place data bits.
		self::place_data( $grid, $all_codewords, $size_modules );

		// 6. Apply best mask.
		$mask = self::apply_best_mask( $grid, $size_modules );

		// 7. Write format information.
		self::write_format_info( $grid, $size_modules, $mask );

		// 8. Render SVG.
		return self::render_svg( $grid, $size_modules, $size, $margin );
	}

	// ── Step 1: Encode data codewords ────────────────────────────────────────

	/**
	 * Encode byte-mode payload into a codeword array.
	 *
	 * @param int[] $bytes   Raw bytes to encode.
	 * @param int   $version QR version.
	 * @return int[]
	 */
	private static function encode_data( $bytes, $version ) {
		$capacity = self::$capacity_m[ $version ];
		$n        = count( $bytes );

		// Bit buffer.
		$bits = array();

		// Mode indicator: byte mode = 0100.
		array_push( $bits, 0, 1, 0, 0 );

		// Character count (8 bits for versions 1-9 byte mode).
		for ( $i = 7; $i >= 0; $i-- ) {
			$bits[] = ( $n >> $i ) & 1;
		}

		// Data bits.
		foreach ( $bytes as $b ) {
			for ( $i = 7; $i >= 0; $i-- ) {
				$bits[] = ( $b >> $i ) & 1;
			}
		}

		// Terminator (up to 4 zero bits).
		$total_bits = $capacity * 8;
		for ( $t = 0; $t < 4 && count( $bits ) < $total_bits; $t++ ) {
			$bits[] = 0;
		}

		// Pad to byte boundary.
		while ( count( $bits ) % 8 !== 0 ) {
			$bits[] = 0;
		}

		// Pad codewords.
		$pad = array( 0xEC, 0x11 );
		$pi  = 0;
		while ( count( $bits ) < $total_bits ) {
			$p = $pad[ $pi % 2 ];
			$pi++;
			for ( $i = 7; $i >= 0; $i-- ) {
				$bits[] = ( $p >> $i ) & 1;
			}
		}

		// Convert bit array to codeword array.
		$codewords = array();
		for ( $i = 0; $i < count( $bits ); $i += 8 ) {
			$cw = 0;
			for ( $j = 0; $j < 8; $j++ ) {
				$cw = ( $cw << 1 ) | ( $bits[ $i + $j ] ?? 0 );
			}
			$codewords[] = $cw;
		}

		return $codewords;
	}

	// ── Step 2: Reed-Solomon ECC ──────────────────────────────────────────────

	private static function init_gf() {
		if ( self::$gf_init ) {
			return;
		}
		self::$gf_init = true;
		$x = 1;
		for ( $i = 0; $i < 255; $i++ ) {
			self::$exp[ $i ] = $x;
			self::$log[ $x ] = $i;
			$x <<= 1;
			if ( $x & 0x100 ) {
				$x ^= 0x11D; // GF(256) primitive polynomial.
			}
		}
		self::$exp[255] = self::$exp[0];
	}

	private static function gf_mul( $a, $b ) {
		if ( 0 === $a || 0 === $b ) {
			return 0;
		}
		return self::$exp[ ( self::$log[ $a ] + self::$log[ $b ] ) % 255 ];
	}

	/**
	 * Compute Reed-Solomon generator polynomial coefficients.
	 *
	 * @param int $n Degree (number of EC codewords).
	 * @return int[]
	 */
	private static function rs_generator( $n ) {
		$g = array( 1 );
		for ( $i = 0; $i < $n; $i++ ) {
			$factor = array( 1, self::$exp[ $i ] );
			$result = array_fill( 0, count( $g ) + 1, 0 );
			foreach ( $g as $gi => $gv ) {
				foreach ( $factor as $fi => $fv ) {
					$result[ $gi + $fi ] ^= self::gf_mul( $gv, $fv );
				}
			}
			$g = $result;
		}
		return array_slice( $g, 1 ); // Drop leading 1.
	}

	/**
	 * Compute EC codewords for one block.
	 *
	 * @param int[] $data Data codewords for this block.
	 * @param int   $n_ec Number of EC codewords required.
	 * @return int[]
	 */
	private static function rs_encode( $data, $n_ec ) {
		$generator = self::rs_generator( $n_ec );
		$remainder = array_fill( 0, $n_ec, 0 );
		foreach ( $data as $b ) {
			$coef = $b ^ array_shift( $remainder );
			$remainder[] = 0;
			foreach ( $generator as $i => $g ) {
				$remainder[ $i ] ^= self::gf_mul( $coef, $g );
			}
		}
		return $remainder;
	}

	/**
	 * Split data into blocks, add EC, and interleave into a final stream.
	 *
	 * @param int[] $data_cw Data codewords.
	 * @param int   $version QR version.
	 * @return int[]
	 */
	private static function add_ec( $data_cw, $version ) {
		list( $b1, $d1, $b2, $d2 ) = self::$block_info[ $version ];
		$n_ec = self::$ec_codewords_m[ $version ];

		$blocks    = array();
		$ec_blocks = array();
		$offset    = 0;

		for ( $i = 0; $i < $b1; $i++ ) {
			$block       = array_slice( $data_cw, $offset, $d1 );
			$offset     += $d1;
			$blocks[]    = $block;
			$ec_blocks[] = self::rs_encode( $block, $n_ec );
		}
		for ( $i = 0; $i < $b2; $i++ ) {
			$block       = array_slice( $data_cw, $offset, $d2 );
			$offset     += $d2;
			$blocks[]    = $block;
			$ec_blocks[] = self::rs_encode( $block, $n_ec );
		}

		// Interleave data codewords.
		$result  = array();
		$max_len = max( array_map( 'count', $blocks ) );
		for ( $col = 0; $col < $max_len; $col++ ) {
			foreach ( $blocks as $blk ) {
				if ( isset( $blk[ $col ] ) ) {
					$result[] = $blk[ $col ];
				}
			}
		}

		// Interleave EC codewords.
		for ( $col = 0; $col < $n_ec; $col++ ) {
			foreach ( $ec_blocks as $blk ) {
				if ( isset( $blk[ $col ] ) ) {
					$result[] = $blk[ $col ];
				}
			}
		}

		return $result;
	}

	// ── Step 3: Build module grid ─────────────────────────────────────────────

	/**
	 * Initialise a module grid with function patterns.
	 * Module values: null = reserved/function, 0 = dark, 1 = light.
	 *
	 * @param int $version QR version.
	 * @param int $sz      Grid size in modules.
	 * @return array Grid of int|null.
	 */
	private static function build_grid( $version, $sz ) {
		// Use 2D array of int|null; null = "data region".
		$grid = array_fill( 0, $sz, array_fill( 0, $sz, null ) );

		// Finder patterns + separators.
		self::place_finder( $grid, 0, 0 );
		self::place_finder( $grid, $sz - 7, 0 );
		self::place_finder( $grid, 0, $sz - 7 );
		self::place_separators( $grid, $sz );

		// Timing patterns.
		for ( $i = 8; $i < $sz - 8; $i++ ) {
			$v          = ( $i % 2 === 0 ) ? 0 : 1;
			$grid[6][ $i ] = $v;
			$grid[ $i ][6] = $v;
		}

		// Dark module.
		$grid[ 4 * $version + 9 ][8] = 0;

		// Alignment patterns.
		if ( $version >= 2 && isset( self::$alignment_coords[ $version ] ) ) {
			$coords = self::$alignment_coords[ $version ];
			foreach ( $coords as $r ) {
				foreach ( $coords as $c ) {
					if ( null === $grid[ $r ][ $c ] ) {
						self::place_alignment( $grid, $r, $c );
					}
				}
			}
		}

		// Reserve format information areas (written later after masking).
		self::reserve_format_areas( $grid, $sz );

		return $grid;
	}

	private static function place_finder( &$grid, $row, $col ) {
		for ( $r = 0; $r < 7; $r++ ) {
			for ( $c = 0; $c < 7; $c++ ) {
				$dark = ( $r === 0 || $r === 6 || $c === 0 || $c === 6 )
					|| ( $r >= 2 && $r <= 4 && $c >= 2 && $c <= 4 );
				$grid[ $row + $r ][ $col + $c ] = $dark ? 0 : 1;
			}
		}
	}

	private static function place_separators( &$grid, $sz ) {
		// Top-left.
		for ( $i = 0; $i < 8; $i++ ) {
			$grid[7][ $i ] = 1;
			$grid[ $i ][7] = 1;
		}
		// Top-right.
		for ( $i = 0; $i < 8; $i++ ) {
			$grid[7][ $sz - 8 + $i ] = 1;
			$grid[ $i ][ $sz - 8 ]   = 1;
		}
		// Bottom-left.
		for ( $i = 0; $i < 8; $i++ ) {
			$grid[ $sz - 8 ][ $i ] = 1;
			$grid[ $sz - 8 + $i ][7] = 1;
		}
	}

	private static function place_alignment( &$grid, $cr, $cc ) {
		for ( $dr = -2; $dr <= 2; $dr++ ) {
			for ( $dc = -2; $dc <= 2; $dc++ ) {
				$dark = ( abs( $dr ) === 2 || abs( $dc ) === 2 || ( $dr === 0 && $dc === 0 ) );
				$grid[ $cr + $dr ][ $cc + $dc ] = $dark ? 0 : 1;
			}
		}
	}

	private static function reserve_format_areas( &$grid, $sz ) {
		// Top-left horizontal + vertical strips around finder.
		for ( $i = 0; $i < 9; $i++ ) {
			if ( null === $grid[8][ $i ] ) {
				$grid[8][ $i ] = 1; // temporary light.
			}
			if ( null === $grid[ $i ][8] ) {
				$grid[ $i ][8] = 1;
			}
		}
		// Top-right + bottom-left format strips.
		for ( $i = 0; $i < 8; $i++ ) {
			if ( null === $grid[8][ $sz - 1 - $i ] ) {
				$grid[8][ $sz - 1 - $i ] = 1;
			}
			if ( null === $grid[ $sz - 7 + $i ][8] ) {
				$grid[ $sz - 7 + $i ][8] = 1;
			}
		}
	}

	// ── Step 4: Place data bits ───────────────────────────────────────────────

	private static function place_data( &$grid, $codewords, $sz ) {
		// Flatten codewords to a bit array.
		$bits = array();
		foreach ( $codewords as $cw ) {
			for ( $i = 7; $i >= 0; $i-- ) {
				$bits[] = ( $cw >> $i ) & 1;
			}
		}

		$bit_idx = 0;
		$up      = true; // Direction.
		$col     = $sz - 1;

		while ( $col > 0 ) {
			if ( $col === 6 ) {
				$col--; // Skip timing column.
			}
			for ( $row_offset = 0; $row_offset < $sz; $row_offset++ ) {
				$row = $up ? ( $sz - 1 - $row_offset ) : $row_offset;
				for ( $dc = 0; $dc <= 1; $dc++ ) {
					$c = $col - $dc;
					if ( null === $grid[ $row ][ $c ] ) {
						$grid[ $row ][ $c ] = ( $bit_idx < count( $bits ) )
							? $bits[ $bit_idx++ ] : 0;
					}
				}
			}
			$col -= 2;
			$up   = ! $up;
		}
	}

	// ── Step 5: Masking ───────────────────────────────────────────────────────

	/** @var callable[] Mask condition functions (by pattern index). */
	private static function mask_condition( $pattern, $r, $c ) {
		switch ( $pattern ) {
			case 0: return ( $r + $c ) % 2 === 0;
			case 1: return $r % 2 === 0;
			case 2: return $c % 3 === 0;
			case 3: return ( $r + $c ) % 3 === 0;
			case 4: return ( (int) floor( $r / 2 ) + (int) floor( $c / 3 ) ) % 2 === 0;
			case 5: return ( $r * $c ) % 2 + ( $r * $c ) % 3 === 0;
			case 6: return ( ( $r * $c ) % 2 + ( $r * $c ) % 3 ) % 2 === 0;
			case 7: return ( ( $r + $c ) % 2 + ( $r * $c ) % 3 ) % 2 === 0;
		}
		return false;
	}

	private static function apply_mask( $grid, $sz, $pattern ) {
		$masked = $grid;
		for ( $r = 0; $r < $sz; $r++ ) {
			for ( $c = 0; $c < $sz; $c++ ) {
				// Only mask data modules (null was replaced in place_data).
				// Function modules have non-null values set by build_grid.
				// After place_data all modules are int. We need to distinguish
				// function from data — we do that by checking format areas
				// which are all set to 1 by reserve_format_areas.
				// Simpler: we re-apply only where the original grid had null.
				// But we've already filled nulls in place_data. So we just
				// XOR every module that is NOT inside the finder/separator/
				// timing/alignment/format areas.  The easiest approach: mask
				// only cells that are purely data, i.e., not one of the
				// function-pattern cells.  We detect function cells by checking
				// if they're in the function-reserved regions.
				if ( self::is_data_module( $r, $c, $sz ) ) {
					if ( self::mask_condition( $pattern, $r, $c ) ) {
						$masked[ $r ][ $c ] = $masked[ $r ][ $c ] ^ 1;
					}
				}
			}
		}
		return $masked;
	}

	private static function is_data_module( $r, $c, $sz ) {
		// Finder + separator regions.
		if ( $r < 9 && $c < 9 ) return false;
		if ( $r < 9 && $c >= $sz - 8 ) return false;
		if ( $r >= $sz - 8 && $c < 9 ) return false;
		// Timing patterns.
		if ( $r === 6 || $c === 6 ) return false;
		// Format information columns/rows.
		if ( $r === 8 && $c <= 8 ) return false;
		if ( $c === 8 && $r <= 8 ) return false;
		if ( $r === 8 && $c >= $sz - 8 ) return false;
		if ( $c === 8 && $r >= $sz - 7 ) return false;
		return true;
	}

	private static function score_mask( $grid, $sz ) {
		$score = 0;

		// Penalty 1: 5+ consecutive same-color modules in row/column.
		for ( $r = 0; $r < $sz; $r++ ) {
			$run = 1;
			for ( $c = 1; $c < $sz; $c++ ) {
				if ( $grid[ $r ][ $c ] === $grid[ $r ][ $c - 1 ] ) {
					$run++;
					if ( $run === 5 ) $score += 3;
					elseif ( $run > 5 ) $score++;
				} else {
					$run = 1;
				}
			}
		}
		for ( $c = 0; $c < $sz; $c++ ) {
			$run = 1;
			for ( $r = 1; $r < $sz; $r++ ) {
				if ( $grid[ $r ][ $c ] === $grid[ $r - 1 ][ $c ] ) {
					$run++;
					if ( $run === 5 ) $score += 3;
					elseif ( $run > 5 ) $score++;
				} else {
					$run = 1;
				}
			}
		}

		// Penalty 2: 2×2 same-color blocks.
		for ( $r = 0; $r < $sz - 1; $r++ ) {
			for ( $c = 0; $c < $sz - 1; $c++ ) {
				$v = $grid[ $r ][ $c ];
				if ( $grid[ $r ][ $c + 1 ] === $v
					&& $grid[ $r + 1 ][ $c ] === $v
					&& $grid[ $r + 1 ][ $c + 1 ] === $v ) {
					$score += 3;
				}
			}
		}

		// Penalty 3: finder-like patterns.
		$p3a = array( 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0 );
		$p3b = array( 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1 );
		for ( $r = 0; $r < $sz; $r++ ) {
			for ( $c = 0; $c <= $sz - 11; $c++ ) {
				$row_match_a = true;
				$row_match_b = true;
				for ( $k = 0; $k < 11; $k++ ) {
					if ( $grid[ $r ][ $c + $k ] !== $p3a[ $k ] ) $row_match_a = false;
					if ( $grid[ $r ][ $c + $k ] !== $p3b[ $k ] ) $row_match_b = false;
				}
				if ( $row_match_a || $row_match_b ) $score += 40;
			}
		}
		for ( $c = 0; $c < $sz; $c++ ) {
			for ( $r = 0; $r <= $sz - 11; $r++ ) {
				$col_match_a = true;
				$col_match_b = true;
				for ( $k = 0; $k < 11; $k++ ) {
					if ( $grid[ $r + $k ][ $c ] !== $p3a[ $k ] ) $col_match_a = false;
					if ( $grid[ $r + $k ][ $c ] !== $p3b[ $k ] ) $col_match_b = false;
				}
				if ( $col_match_a || $col_match_b ) $score += 40;
			}
		}

		// Penalty 4: proportion of dark modules.
		$dark = 0;
		$total = $sz * $sz;
		for ( $r = 0; $r < $sz; $r++ ) {
			for ( $c = 0; $c < $sz; $c++ ) {
				if ( $grid[ $r ][ $c ] === 0 ) $dark++;
			}
		}
		$pct  = (int) round( $dark / $total * 100 );
		$prev = (int) floor( $pct / 5 ) * 5;
		$next = (int) ceil( $pct / 5 ) * 5;
		$score += min( abs( $prev - 50 ), abs( $next - 50 ) ) / 5 * 10;

		return $score;
	}

	private static function apply_best_mask( &$grid, $sz ) {
		$best_score = PHP_INT_MAX;
		$best_mask  = 0;
		$best_grid  = $grid;

		for ( $m = 0; $m < 8; $m++ ) {
			$candidate = self::apply_mask( $grid, $sz, $m );
			$score     = self::score_mask( $candidate, $sz );
			if ( $score < $best_score ) {
				$best_score = $score;
				$best_mask  = $m;
				$best_grid  = $candidate;
			}
		}

		$grid = $best_grid;
		return $best_mask;
	}

	// ── Step 6: Write format information ─────────────────────────────────────

	private static function write_format_info( &$grid, $sz, $mask ) {
		$fmt = self::$format_info[ $mask ];

		// Top-left horizontal (columns 0-5, skip 6=timing, 7, 8).
		$positions_h = array( 0, 1, 2, 3, 4, 5, 7, 8 );
		// Top-left vertical (rows 0-5, skip 6=timing, 7, 8).
		$positions_v = array( 8, 7, 5, 4, 3, 2, 1, 0 );

		for ( $i = 0; $i < 8; $i++ ) {
			$bit = ( $fmt >> ( 14 - $i ) ) & 1;
			$grid[8][ $positions_h[ $i ] ] = $bit;
			$grid[ $positions_v[ $i ] ][8] = $bit;
		}
		// Bit 6 (index 8 of 15) goes to row8/col8 corners.
		$grid[8][8] = ( $fmt >> 7 ) & 1;

		// Top-right (columns sz-8 to sz-1, row 8).
		for ( $i = 0; $i < 8; $i++ ) {
			$grid[8][ $sz - 8 + $i ] = ( $fmt >> $i ) & 1;
		}

		// Bottom-left (rows sz-7 to sz-1, col 8).
		for ( $i = 0; $i < 7; $i++ ) {
			$grid[ $sz - 7 + $i ][8] = ( $fmt >> ( 13 - $i ) ) & 1;
		}
	}

	// ── Step 7: Render SVG ────────────────────────────────────────────────────

	/**
	 * Convert the module grid to an inline SVG string.
	 *
	 * @param array $grid Grid of 0|1 (0=dark, 1=light).
	 * @param int   $sz   Grid size in modules.
	 * @param int   $px   Desired pixel size.
	 * @param int   $margin Quiet zone in modules.
	 * @return string SVG markup.
	 */
	private static function render_svg( $grid, $sz, $px, $margin ) {
		$total     = $sz + $margin * 2;
		$cell      = $px / $total;
		$cell_r    = round( $cell, 4 );

		$svg  = sprintf(
			'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %1$s %1$s" width="%2$s" height="%2$s" role="img" aria-label="QR Code">',
			$total,
			$px
		);
		// White background.
		$svg .= sprintf( '<rect width="%1$s" height="%1$s" fill="#fff"/>', $total );

		// Dark modules as rects.
		for ( $r = 0; $r < $sz; $r++ ) {
			for ( $c = 0; $c < $sz; $c++ ) {
				if ( 0 === (int) $grid[ $r ][ $c ] ) {
					$svg .= sprintf(
						'<rect x="%s" y="%s" width="1" height="1" fill="#000"/>',
						$c + $margin,
						$r + $margin
					);
				}
			}
		}

		$svg .= '</svg>';
		return $svg;
	}
}
